[general]
import = ["/home/shashank/.cache/wal/colors-alacritty.toml"]

[window]
opacity = 1.0
padding.x = 20
padding.y = 20
decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[cursor]
style.shape = "Block"
style.blinking = "Never"

[font]
normal.family = "Iosevka NFM"
normal.style = "Medium"
size = 15.0
offset.x = 0
offset.y = 1
